name: C/C++ CI
on: [push]

jobs:
  ubuntu_native_hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: install packages
        run: |
           sudo apt-get update -m && sudo apt-get -y install libiio-dev llibiio-utilsibglib2.0-dev libgtk2.0-dev libgtkdatabox-dev libmatio-dev libfftw3-dev libxml2 libxml2-dev bison flex libavahi-common-dev libavahi-client-dev libcurl4-openssl-dev libjansson-dev cmake libaio-dev libusb-1.0-0-dev libserialport-dev libxml2-dev doxygen graphviz
        shell: bash
      - name: Build Linux native executable
        uses: lukka/run-cmake@v0
        with:
          #cmakeListsOrSettingsJson: CMakeSettingsJson
          configurationRegexFilter: 'Linux-Release'
