name: C/C++ CI
on: [push]

jobs:
  ubuntu_native_hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: install packages
        run: |
          sudo apt-get update -m && sudo apt-get install xorg-dev libglu1-mesa-dev libalut-dev
        shell: bash
      - name: Build Linux native executable
        uses: lukka/run-cmake@v0
        with:
          #cmakeListsOrSettingsJson: CMakeSettingsJson
          configurationRegexFilter: 'Linux-Release'
